name: Self-Hosted CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter (if available)
        run: npm run lint || echo "No lint script found"
        continue-on-error: true
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Build application
        run: npm run build || echo "No build script found"
        continue-on-error: true
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dist-${{ matrix.node-version }}
          path: |
            dist
            build
            *.js
            package.json
            package-lock.json
          retention-days: 7

  health-check:
    runs-on: self-hosted
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start server in background
        run: |
          nohup npm start > server.log 2>&1 &
          echo $! > server.pid
          sleep 5
      
      - name: Health check
        run: |
          max_attempts=10
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if curl -f http://localhost:3001/health; then
              echo "Health check passed"
              exit 0
            fi
            attempt=$((attempt + 1))
            echo "Attempt $attempt failed, retrying..."
            sleep 2
          done
          echo "Health check failed after $max_attempts attempts"
          exit 1
      
      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi
      
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server.log
          retention-days: 3

  deploy:
    runs-on: self-hosted
    needs: [build-and-test, health-check]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --production
      
      - name: Deploy notification
        run: |
          echo "Deploying cruis-api to self-hosted environment"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Author: ${{ github.actor }}"
      
      - name: Restart application
        run: |
          # Add your deployment commands here
          # For example:
          # pm2 restart cruis-api || pm2 start index.js --name cruis-api
          # Or use systemctl if running as a service:
          # sudo systemctl restart cruis-api
          echo "Application deployment completed"
